baseURL = 'https://syedmammar123.github.io/'
languageCode = 'en-us'
title = 'A blog site by Ammar'

paginate = 3

[params]
 description = "A blog by Ammar"
 dateFormat = "Jan 2, 2006"

[taxonomies]
 author = "authors"
 categories = "categories"