baseURL = 'https://syedmammar123.github.io/Blog-Site-Using-Hugo/'
languageCode = 'en-us'
title = 'My Personal Blog'

paginate = 3

[params]
 description = "A blog by Ammar"
 dateFormat = "Jan 2, 2006"

[taxonomies]
 author = "authors"
 categories = "categories"